### ISSUE TITLE
Probably provide support for tabula also

### ISSUE THREAD

**Issue by soodoku** [sckott/extractr#8]
http://tabula.technology/ (gets tables from pdfs)

It is generally a bit worse than abbyy and capticrity but it is free

**Comment by sckott** [comment]
@soodoku Does Tabula allow programmatic access?  I don't see that anywhere

**Comment by soodoku** [comment]
Righto. We can always just call tabula from system() no? and then track the out. Though see this:
https://github.com/tabulapdf/tabula-api

**Comment by sckott** [comment]
Hmm, i'd like to avoid making system calls. Let's wait to see if the Tabula API becomes useable - that seems like a good option

**Comment by abresler** [comment]
You would enter FULL GOD MODE if that happens -- I think there is an API in
1.0 from playing around with it {note it only works in fire fox}  -- if you
ask for a script it gives you the bash script with an API call:

https://github.com/tabulapdf/tabula

---

_Alex Bresler_
abresler@asbcllc.com

​www.asbcllc.com​

917-455-0239
​ (cell)​

@abresler http://twitter.com/abresler | LinkedIn
http://www.linkedin.com/in/abresler | My Musings http://asbcllc.com/blog

On Tue, Aug 11, 2015 at 4:24 PM, Scott Chamberlain <notifications@github.com

**Comment by abresler** [comment]
The API works well the issue is that the autodetection is very poor and the only way to make use of the power of tabula is to use the GUI and draw the box over the table to get out the X-Y coordinates which is needed to make the API useful.

This isnt the right place I bet but one cool thing for a possible RStudio feature is to itegrate in an upload PDF option where there is a Tabula style pain where you can extract out the data and turn it into a data frame

Here is the baseline output from my example 

```
tabula --no-spreadsheet -a 72.765,51.48,428.175,760.32 -p 1 "$1"
tabula --no-spreadsheet -a 96.008,66.555,639.923,579.105 -p 2 "$1"
[
    {
        "x1": 51.48,
        "x2": 760.3199999999999,
        "y1": 72.765,
        "y2": 428.175,
        "width": 708.84,
        "height": 355.41,
        "page": 1,
        "extraction_method": "original",
        "selection_id": "D1439324936040"
    },
    {
        "x1": 66.555,
        "x2": 579.105,
        "y1": 96.00750000000001,
        "y2": 639.9225,
        "width": 512.55,
        "height": 543.915,
        "page": 2,
        "extraction_method": "original",
        "selection_id": "V1439324946636"
    }
]
```

As a general thing if the R community embraced the recent evolution in OCR it would be a hugely advantagous in getting people to pick R as their do it all language.

<img width="750" alt="screen shot 2015-08-11 at 4 33 21 pm" src="https://cloud.githubusercontent.com/assets/740564/9209866/cf4269bc-4046-11e5-8f12-2cc2ce75ec7c.png">

**Comment by sckott** [comment]
> You would enter FULL GOD MODE if that happens

ha ha, does that mean the pkg gets through CRAN without review?

**Comment by abresler** [comment]
CRAN????  It should -- I dont mess with Politboros!

---

_Alex Bresler_
abresler@asbcllc.com

​www.asbcllc.com​

917-455-0239
​ (cell)​

@abresler http://twitter.com/abresler | LinkedIn
http://www.linkedin.com/in/abresler | My Musings http://asbcllc.com/blog

On Tue, Aug 11, 2015 at 4:49 PM, Scott Chamberlain <notifications@github.com

**Comment by sckott** [comment]
@abresler thanks for the example. Right, i thought that even with the Tabula API you'd still need some amount of GUI based interaction - which isn't ideal for reproducibility, but worth a try probably. 

Good idea about Rstudio, could ask some of those kids if they're interested.

**Comment by sckott** [comment]
looks like the API is still on their list of things to do https://twitter.com/jeremybmerrill/status/631545261207199744  

> Yes, it's still on the road map!
